### ISSUE TITLE
Version 1.2.0 package is lacking attach.js .

### ISSUE THREAD

**Issue by elfmimi** [Unity-Technologies/vscode-unity-debug#34]
Version 1.2.0 package is lacking attach.js .

After updating, 1.1.0 -> 1.2.0 ,
&gt;Unity Attach Debugger
fails with the following error.
"[Error] command 'attach.attachToDebugger' not found"

**Comment by EvansThomas** [comment]
Is there a fix for this? I need to have 2 Unity projects open at the same time, and this is forcing me to close a project every time I need to debug something.

**Comment by elfmimi** [comment]
For now, what you can do is to get this
https://github.com/Unity-Technologies/vscode-unity-debug/blob/master/attach.js
and put it here
~/.vscode/extensions/Unity.unity-debug-1.2.0/attach.js
.

**Comment by lukaszunity** [comment]
Fixed in published version 1.2.1

**Comment by EvansThomas** [comment]
Even after attach.js has been added, I'm not able to debug when multiple instances of Unity are open.
![dropdown](https://user-images.githubusercontent.com/451684/27681489-14a52878-5cdd-11e7-9c9e-e44616b90a1f.png)
When I choose one from the dropdown, I still get the following error:
![multipletargets](https://user-images.githubusercontent.com/451684/27681508-269c566e-5cdd-11e7-90da-9dc7362e921b.png)
