### ISSUE TITLE
Project opens like workspace

### ISSUE THREAD

**Issue by dps999** [Unity-Technologies/vscode-unity-debug#67]
After latest update of VSCode Unity open project like new workspace and every separate script file it open like new workspace every time.

Official support of VSCode said that it is extension problem, we would just close workspace and it will never back.

Would be great to get rid of the workspaces and work like before in the single project.

Thank you!

**Comment by lukaszunity** [comment]
Which version of unity has this issue?

**Comment by dps999** [comment]
I got the issue in any versions i have 5.6.1, 2017.1, 2017.2

**Comment by lukaszunity** [comment]
Has this been fixed? I believe is a regression in VS Code 1.18. I think VS Code 1.17.2 does not have this issue.

**Comment by dps999** [comment]
Hi,
 thank you for update.

This issue still happens.
Problem is when i open project from Unity menu Assets/Open c# project. - we got workspace 
But if i click on single script in Unity  - it opens separate simple project. 

So i manually open simple project via open folder and it works fine.

**Comment by dps999** [comment]
This problem only happen when you are trying to open c# project from Unity via Assets-> Open c# project

**Comment by gabstv** [comment]
To avoid having to save a new VSCode project every time, I usually open the code project once (not via Unity). To get the latest compiled intellisense (or if VSCode/omnisharp is complaining about some missing reference), I press ```cmd+shift+p (open command prompt) > reload window```

![screen shot 2018-05-02 at 10 12 52](https://user-images.githubusercontent.com/1563110/39525127-83aa0364-4df1-11e8-985c-658633f27f69.png)


This is my workaround at the moment.

**Comment by zmicx** [comment]
Opening C# project by click UnityMenu/Asset will get a Untitled worldspace each time. However, Clicking a C# script in Project view or Clicking output in Console View will get foldopend.
Operation: Win10
Unity: 2017.1.3.p2
VsCode: 1.23.1

**Comment by miniwolf** [comment]
@zmicx This sounds like there is a problem in how Unity is parsing the arguments to VS Code. The scripts are opened using `folder -r -g file:line`. Where `-r` will reuse the window instead of opening a new window. The `folder` will be the workspace. I can have a look at it.

**Comment by stefano-rocco** [comment]
@miniwolf Not sure if it's related with this issue, I'm using VsCode Insiders and after updating Unity to the latest version, whenever I opened a script from Unity, it would be opened as a single file, rather than in the context of a workspace. (Meaning that VsCode wasn't opening the project's workspace in the first place, or rather simply the project's folder in my case, which contains the .csproj files.) This problem didn't occur with the stable version of VsCode. Btw, for the former, I seem to have solved using: `"$(ProjectPath)" -r -g "$(File):$(Line)"`

OS: Windows 7
Unity: 2018.1.1f1
VsCode: 1.25.0-insider

**Comment by miniwolf** [comment]
@stefano-rocco I don't know of any upcoming changes to VS Code command line arguments, so everything should be working with the newest Unity. However, most of the code regarding script editors are being rewritten, to both expose arguments sent to VS Code, and also to make it easier to support different editors. But that rewrite of Unity will take some time.

**Comment by rileypb** [comment]
This happens for me in 2018.2.b6 on High Sierra, for Sublime Text 3.1.1, and TextWrangler 5.5.2.

**Comment by miniwolf** [comment]
@rileypb if you are experiencing problems with this, it may be resolved through the changes that I have upcoming. However this extension is dealing with visual studio code, and not Sublime Text or TextWrangler. If you are experiencing usability problems with those two, I would suggest reporting these issues as a bug to Unity directly.

**Comment by chadstitch** [comment]
I too am still experiencing this problem with Unity 2017.4.2f2

**Comment by miniwolf** [comment]
I am closing this issue as there hasn't been any activity for a while.
Opening vscode from unity, is a unity specific feature. As unity will call vscode with the correct arguments, by use of the vscode unity package. Therefore not a vscode debugger extension problem
